version: '3.9'
services:
  ethereum-contracts:
    container_name: ethereum-contracts
    volumes:
      # vscode
      - vscode-exts:/root/.vscode-server/extensions
      - vscode-exts-insiders:/root/.vscode-server-insiders/extensions
        # k8s
      - ~/.kube/config:/home/node/.kube/config
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  vscode-exts:
  vscode-exts-insiders:
